# Generated by Django 3.1.1 on 2020-09-08 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_brand', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_color', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=200)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField(default='')),
                ('product_created_date', models.DateTimeField(auto_now_add=True)),
                ('product_updated_date', models.DateTimeField(auto_now_add=True)),
                ('product_sell_price', models.IntegerField(default=0)),
                ('product_mrp_price', models.IntegerField(default=0)),
                ('product_offer', models.IntegerField(default=0)),
                ('product_image', models.ImageField(upload_to='store/images/')),
                ('product_available', models.BooleanField(default=True)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productbrand')),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productcolor')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productsize')),
                ('subcategory_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.subcategory')),
            ],
        ),
    ]
