# Generated by Django 3.1.1 on 2020-09-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-product_created_date']},
        ),
        migrations.AlterModelOptions(
            name='productbrand',
            options={'verbose_name_plural': 'ProductBrands'},
        ),
        migrations.AlterModelOptions(
            name='productcolor',
            options={'verbose_name_plural': 'ProductColors'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name_plural': 'ProductSizes'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Subategories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_mrp_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_offer',
        ),
    ]
