# Generated by Django 3.1.1 on 2020-09-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200909_0354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_created_date']},
        ),
    ]
